apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: qute-kafka
spec:
  flows:
    - from:
        uri: "kafka:inbound"
        steps:
          - to: 'log:info'
          - to:
              uri: "kafka:outbound"
  traits:
    camel:
      properties:
        - camel.component.kafka.brokers=<kafka-broker-id>
        - camel.component.kafka.security-protocol=SASL_SSL
        - camel.component.kafka.sasl-mechanism=PLAIN
        - camel.component.kafka.sasl-jaas-config=org.apache.kafka.common.security.plain.PlainLoginModule required
          username='<client-id>'
          password='<client-secret>';